remote_theme: "mmistakes/minimal-mistakes@4.24.0"

liquid:
  error_mode: strict
  strict_filters: true

exclude:
  - Makefile
  - .github

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-emoji
