# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
  - number: 1007
  - number: 1015
  - number: 58

filters:
- name: only_jlc_parts
  comment: Only parts with JLC (LCSC) code
  type: generic
  include_only:
  - column: LCSC#
    regex: ^C\d+

variants:
- name: place_holder
  comment: Just a place holder for pre_transform filters
  type: kicost
  pre_transform:
  - _kicost_rename
  - _rot_footprint

outputs:
- name: basic_boardview
  comment: Board View export
  type: boardview
  dir: Assembly

- name: generic_bom_xlsx
  comment: Generic Bill of Materials in XLSX format
  type: bom
  dir: BoM/Generic
  options:
    format: XLSX
    count_smd_tht: true

- name: gerber_modern
  comment: Gerbers in modern format, recommended by the standard
  type: gerber
  dir: Gerbers_and_Drill
  layers:
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: B.Paste
    suffix: B_Paste
    description: Bottom solder paste
  - layer: B.Silkscreen
    suffix: B_Silkscreen
    description: Bottom silkscreen (artwork)
  - layer: F.Silkscreen
    suffix: F_Silkscreen
    description: Front silkscreen (artwork)
  - layer: B.Mask
    suffix: B_Mask
    description: Bottom soldermask (negative)
  - layer: F.Mask
    suffix: F_Mask
    description: Front soldermask (negative)
  - layer: User.Drawings
    suffix: User_Drawings
    description: User drawings
  - layer: User.Comments
    suffix: User_Comments
    description: User comments
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
  - layer: B.Courtyard
    suffix: B_Courtyard
    description: Bottom courtyard area
  - layer: F.Courtyard
    suffix: F_Courtyard
    description: Front courtyard area
  - layer: B.Fab
    suffix: B_Fab
    description: Bottom documentation
  - layer: F.Fab
    suffix: F_Fab
    description: Front documentation

- name: JLCPCB_gerbers
  comment: Gerbers compatible with JLCPCB
  type: gerber
  dir: Manufacturers/JLCPCB
  options:
    exclude_edge_layer: true
    exclude_pads_from_silkscreen: true
    plot_sheet_reference: false
    plot_footprint_refs: true
    plot_footprint_values: false
    force_plot_invisible_refs_vals: false
    tent_vias: true
    use_protel_extensions: true
    create_gerber_job_file: false
    disable_aperture_macros: true
    gerber_precision: 4.6
    use_gerber_x2_attributes: false
    use_gerber_net_attributes: false
    line_width: 0.1
    subtract_mask_from_silk: true
    inner_extension_pattern: .gp%n
  layers: &id002
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: B.Paste
    suffix: B_Paste
    description: Bottom solder paste
  - layer: B.Silkscreen
    suffix: B_Silkscreen
    description: Bottom silkscreen (artwork)
  - layer: F.Silkscreen
    suffix: F_Silkscreen
    description: Front silkscreen (artwork)
  - layer: B.Mask
    suffix: B_Mask
    description: Bottom soldermask (negative)
  - layer: F.Mask
    suffix: F_Mask
    description: Front soldermask (negative)
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
- name: JLCPCB_drill
  comment: Drill files compatible with JLCPCB
  type: excellon
  dir: Manufacturers/JLCPCB
  options:
    pth_and_npth_single_file: false
    pth_id: -PTH
    npth_id: -NPTH
    metric_units: true
    map: gerber
    route_mode_for_oval_holes: false
    output: '%f%i.%x'
- name: JLCPCB_position
  comment: Pick and place file, JLCPCB style
  type: position
  dir: Manufacturers/JLCPCB
  options:
    variant: place_holder
    output: '%f_cpl_jlc.%x'
    format: CSV
    units: millimeters
    separate_files_for_front_and_back: false
    only_smd: true
    columns:
    - id: Ref
      name: Designator
    - Val
    - Package
    - id: PosX
      name: Mid X
    - id: PosY
      name: Mid Y
    - id: Rot
      name: Rotation
    - id: Side
      name: Layer
- name: JLCPCB_bom
  comment: BoM for JLCPCB
  type: bom
  dir: Manufacturers/JLCPCB
  options:
    output: '%f_%i_jlc.%x'
    exclude_filter: only_jlc_parts
    ref_separator: ','
    columns:
    - field: Value
      name: Comment
    - field: References
      name: Designator
    - Footprint
    - field: LCSC#
      name: 'LCSC Part #'
    csv:
      hide_pcb_info: true
      hide_stats_info: true
      quote_all: true
- name: JLCPCB
  comment: ZIP file for JLCPCB
  type: compress
  dir: Manufacturers
  options:
    files:
    - from_output: JLCPCB_gerbers
      dest: /
    - from_output: JLCPCB_drill
      dest: /
    - from_output: JLCPCB_position
      dest: /
    - from_output: JLCPCB_bom
      dest: /

- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: Assembly

- name: basic_pcb_print_pdf
  comment: PCB
  type: pcb_print
  dir: PCB/PDF
  options:
    format: PDF
    pages:
    - layers:
      - layer: F.Cu
      - layer: F.Mask
        color: '#14332440'
      - layer: F.Silkscreen
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      sheet: Front copper
    - layers:
      - layer: B.Cu
      - layer: B.Mask
        color: '#14332440'
      - layer: B.Paste
      - layer: B.Silkscreen
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      mirror: true
      sheet: Bottom copper
    - layers:
      - layer: B.Courtyard
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      mirror: true
      sheet: Bottom courtyard area
    - layers:
      - layer: F.Courtyard
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      sheet: Front courtyard area
    - layers:
      - layer: B.Fab
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      mirror: true
      sheet: Bottom documentation
    - layers:
      - layer: F.Fab
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      sheet: Front documentation
    keep_temporal_files: true


- name: basic_pcbdraw_png_set_red_hasl_top
  comment: PCB 2D render in PNG format, using set-red-hasl style
  type: pcbdraw
  dir: PCB/2D_render/set_red_hasl
  options:
    style: set-red-hasl
    format: png

- name: basic_pcbdraw_png_set_red_hasl_bottom
  comment: PCB 2D render in PNG format, using set-red-hasl style
  type: pcbdraw
  dir: PCB/2D_render/set_red_hasl
  options:
    style: set-red-hasl
    format: png
    bottom: true
 
- name: basic_pdf_sch_print
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: Schematic
- name: basic_svg_sch_print
  comment: Schematic in SVG format
  type: svg_sch_print
  dir: Schematic

- name: basic_render_3d_top
  comment: 3D view from top
  type: render_3d
  dir: 3D
  options:
    ray_tracing: true
    orthographic: true
- name: basic_render_3d_30deg
  comment: 3D view from 30 degrees
  type: render_3d
  dir: 3D
  output_id: 30deg
  options:
    ray_tracing: true
    rotate_x: 3
    rotate_z: -2
- name: basic_render_3d_bottom
  comment: 3D view from bottom
  type: render_3d
  dir: 3D
  options:
    ray_tracing: true
    orthographic: true
    view: bottom
